#/etc/pacman.d/mirrorlist
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector -f 100 -l 100 --number 50 --save /etc/pacman.d/mirrorlist
# When:       2020-11-01 05:37:14 UTC
# From:       https://www.archlinux.org/mirrors/status/json/
# Retrieved:  2020-11-01 05:34:22 UTC
# Last Check: 2020-11-01 04:09:28 UTC

Server = https://arch.mirror.constant.com/$repo/os/$arch
Server = https://archmirror1.octyl.net/$repo/os/$arch
Server = https://mirror.pkgbuild.com/$repo/os/$arch
Server = https://mirror.bethselamin.de/$repo/os/$arch
Server = http://arch.hu.fo/archlinux/$repo/os/$arch
Server = https://arch.hu.fo/archlinux/$repo/os/$arch
Server = https://mirror.chaoticum.net/arch/$repo/os/$arch
Server = https://mirror.23media.com/archlinux/$repo/os/$arch
Server = https://mirror.cyberbits.eu/archlinux/$repo/os/$arch
Server = https://archlinux.thaller.ws/$repo/os/$arch
Server = https://archlinux.uk.mirror.allworldit.com/archlinux/$repo/os/$arch
Server = https://mirror.orbit-os.com/archlinux/$repo/os/$arch
Server = https://mirror.wtnet.de/arch/$repo/os/$arch
Server = http://arlm.tyzoid.com/$repo/os/$arch
Server = https://arch.jensgutermuth.de/$repo/os/$arch
Server = https://archlinux.mailtunnel.eu/$repo/os/$arch
Server = https://arlm.tyzoid.com/$repo/os/$arch
Server = http://mirror.csclub.uwaterloo.ca/archlinux/$repo/os/$arch
Server = https://mirror.pseudoform.org/$repo/os/$arch
Server = https://mirror.f4st.host/archlinux/$repo/os/$arch
Server = https://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
Server = https://ftp.sh.cvut.cz/arch/$repo/os/$arch
Server = http://arch.mirror.constant.com/$repo/os/$arch
Server = http://mirror.pseudoform.org/$repo/os/$arch
Server = https://mirror.neuf.no/archlinux/$repo/os/$arch
Server = https://archlinux.dynamict.se/$repo/os/$arch
Server = https://mirror.dkm.cz/archlinux/$repo/os/$arch
Server = http://archmirror1.octyl.net/$repo/os/$arch
Server = http://mirror.chaoticum.net/arch/$repo/os/$arch
Server = http://archlinux.honkgong.info/$repo/os/$arch
Server = http://archlinux.thaller.ws/$repo/os/$arch
Server = http://arch.jensgutermuth.de/$repo/os/$arch
Server = https://archlinux.mirror.digitalpacific.com.au/$repo/os/$arch
Server = http://mirror.orbit-os.com/archlinux/$repo/os/$arch
Server = http://mirror.23media.com/archlinux/$repo/os/$arch
Server = http://mirror.f4st.host/archlinux/$repo/os/$arch
Server = http://ftp.sh.cvut.cz/arch/$repo/os/$arch
Server = http://mirror.cyberbits.eu/archlinux/$repo/os/$arch
Server = http://archlinux.mailtunnel.eu/$repo/os/$arch
Server = http://phinau.de/arch/$repo/os/$arch
Server = https://phinau.de/arch/$repo/os/$arch
Server = http://mirror.wtnet.de/arch/$repo/os/$arch
Server = http://ftp.halifax.rwth-aachen.de/archlinux/$repo/os/$arch
Server = http://archlinux.dynamict.se/$repo/os/$arch
Server = http://mirrors.atviras.lt/archlinux/$repo/os/$arch
